### ISSUE TITLE
I got this error for tqmd, which version do u install?

### ISSUE THREAD

**Issue by usccolumbia** [mm04926412/Site-Net#1]
python create_mp_gap_hdf5.py --cubic_supercell -s 100
2022-11-08 22:15:37 INFO     Initialized benchmark 'matbench_v0.1' with 13 tasks: 
['matbench_dielectric',
 'matbench_expt_gap',
 'matbench_expt_is_metal',
 'matbench_glass',
 'matbench_jdft2d',
 'matbench_log_gvrh',
 'matbench_log_kvrh',
 'matbench_mp_e_form',
 'matbench_mp_gap',
 'matbench_mp_is_metal',
 'matbench_perovskites',
 'matbench_phonons',
 'matbench_steels']
2022-11-08 22:15:37 INFO     Loading dataset 'matbench_mp_gap'...
2022-11-08 22:17:10 INFO     Dataset 'matbench_mp_gap loaded.
Traceback (most recent call last):
  File "/home/xx/Site-Net-/create_mp_gap_hdf5.py", line 201, in <module>
    dataset_to_hdf5(train_inputs,train_outputs,h5_file_name + "_train",pool,fold_n,supercell,supercell_size)
  File "/home/xx/Site-Net-/create_mp_gap_hdf5.py", line 160, in dataset_to_hdf5
    i for i in tqdm(pool.imap(processor.process_structure, [i[1] for i in structure_list]))
TypeError: 'module' object is not callable

**Comment by mm04926412** [comment]
I haven't had any issues with the latest version on conda for python 3.9. I recognise the error from when "import tqdm" is used instead of "from tqdm import tqdm".

What version are you using that gets this error? I can try to reproduce it. I'll post the details of my environment when I am able later today.

**Comment by usccolumbia** [comment]
can u try first putting your sequence into a file
>1
AAKTHHMM

and then  upload the file, and hit predict button?


Jianjun Hu
-----------------------------------------------------------------
Professor, Graduate Recruiting Director
Department of Computer Science and Engineering
University of South Carolina
2223 Storey Innovation Center
550 Assembly Street, Columbia, SC, 29201
Lab page: http://mleg.cse.sc.edu<http://mleg.cse.sc.edu/>
Publication: Google Scholar link<https://scholar.google.com/citations?hl=en&user=_iD3nyMAAAAJ&view_op=list_works&sortby=pubdate>
Research Areas: AI&ML&DL for materials informatics, bioinformatics, health informatics, and intelligent manufacturing.

________________________________

**Comment by mm04926412** [comment]
Hi, sorry I'm not sure what you mean by this? What is AAKTHHMM and the predict button?

**Comment by mm04926412** [comment]
On my environment where things are working its python 3.8.12 and it is tqdm 4.62.3

**Comment by mm04926412** [comment]
tqdm was being overwritten by one of the other imports which had started importing tqdm as a module in its own preamble, it should work now if you pull the latest commit. Please don't hesitage to ask if there are further issues.
